### ISSUE TITLE
surprising interactions between      // values and data nodes

### ISSUE THREAD

**Issue by Amedeo91** [dwd/rapidxml#9]
Hi all,

I found the following issue: I am parsing my XML as following

   vector<char> xml_copy(input_xml.begin(), input_xml.end());
   xml_copy.push_back('\0');
   xml_document<> doc;
   doc.parse<parse_declaration_node>(&xml_copy[0]); // just get the XML declaration

By doing so, I am able to see all my object as well with the CDATA, but if I try to modify some value with the value() method, then only the print() method does not reflect it. However, at node level using the value() method the changes seems to be taken.

I found this issue working at the python binding at the following repository:

https://github.com/Arzaroth/python_rapidxml

Moreover, in the following link I found the following information:
http://www.setnode.com/blog/quick-notes-on-how-to-use-rapidxml/

// we are choosing to parse the XML declaration
// parse_no_data_nodes prevents RapidXML from using the somewhat surprising
// behavior of having both values and data nodes, and having data nodes take
// precedence over values when printing
// >>> note that this will skip parsing of CDATA nodes <<<
doc.parse<parse_declaration_node | parse_no_data_nodes>(&xml_copy[0]);

// alternatively, use one of the two commented lines below to parse CDATA nodes, 
// but please note the above caveat about surprising interactions between 
// values and data nodes (also read http://www.setnode.com/blog/a-rapidxml-gotcha/)
// if you use one of these two declarations try to use data nodes exclusively and
// avoid using value()
//doc.parse<parse_declaration_node>(&xml_copy[0]); // just get the XML declaration
//doc.parse<parse_full>(&xml_copy[0]); // parses everything (slowest)

Currently, I do not need to generate an XML using the parse_declaration_node, therefore I am not going to work on it straight after. However, I guess I might be nice to fix this misbehavior.

Regards,
Amedeo

**Comment by dwd** [comment]
Right. So the underlying issue here is that parse_no_data_nodes can't parse this:

`<element>Some text <em>here</em> and there.</element>`

The element "element" ends up with the value truncated as "Some text ". With parse_no_value, you'll get no value at all, but you'll get child nodes in the sequence "data, element, data" - but you also get the "em" element with no value and a single child data node, which is equally awkward.

RapidXML is trying to help here by letting you pick which awkward you prefer, and defaulting to setting the value of an element to the value of the first data node, which is interestingly weird.

Moreover, CDATA sections are *always* data nodes, and if you turn off data nodes it elides them entirely. Whoops.

I'm going to suggest the following changes:

1) Where an element has a single data node as the sole child on close, we always collapse it *and* drop the data node, **unless** parse_no_value is requested.
2) Where an element has any non-data child nodes, we don't fill the value (claiming it as NULL), **unless** parse_no_data_nodes is requested.
3) parse_fastest might now drop parse_no_data_nodes, even though this behaviour is slightly slower.
